### PR TITLE
Create flutter folder

### PR DESCRIPTION
**Pull request by cisse410**
I create the flutter folder and add into the folder two books by following the CONTRIBUTING file.

### CODE REVIEW

**Comment by mr-mib** [comment]
Hi @cisse410, theses books are very useful. A lot of people have reached out to me asking me to add this kind of books.
Thank you for your support on building a where-to-go library.

Could you please share it with your network so that they can add new books?

**Comment by cisse410** [comment]
@mr-mib It gives me great pleasure to contribute to this wonderful initiative.
I wouldn't hesitate to add more books.

**Comment by cisse410** [comment]
@mr-mib Some of these books are available in this article
https://tonux-dev.com/roadmap-pour-devenir-un-developpeur-flutter-performant/

**Comment by mr-mib** [comment]
Thanks 

Merci

**Pull request merged**
