### PR TITLE
Adding new books & Update 🎊

### PR DESCRIPTION
**Pull request by daoodaba975**
This PR includes updates to the documentation and the addition of new book directories.

The contributors list has been updated with new names and links, and is now displayed in the ReadMe.
New book directories for algorithms, docker, react, engineering, and js have been created, with a total of 21 new books added across these categories.

Great work @mr-mib 👌🏾 keep moving !

### CODE REVIEW

**Review by mr-mib — APPROVED** [review]

**Review by mr-mib — APPROVED** [review]
Nice move!

**Review by mr-mib — APPROVED** [review]
I created a folder named **_data-structures-and-algorithms_** but I think that your proposition is better. Therefore, I'll delete mine.
let's just have a folder named **_algorithms_**

**Review by mr-mib — APPROVED** [review]

**Review by mr-mib — CHANGES_REQUESTED** [review]
Hi @daoodaba975 , what do you think about naming the folder “javascript” instead of “js”?
Or do you have any specific reason to think 'js' is the best fit?

**Comment by daoodaba975** [comment]
> Hi @daoodaba975 , what do you think about naming the folder “javascript” instead of “js”? Or do you have any specific reason to think 'js' is the best fit?

Hi @mr-mib It's just out of habit that I named the folder "js" but I think that "javascript" is much more explicit!

**Comment by daoodaba975** [comment]
> I created a folder named **_data-structures-and-algorithms_** but I think that your proposition is better. Therefore, I'll delete mine. let's just have a folder named **_algorithms_**

Great!!

**Comment by daoodaba975** [comment]
@mr-mib I also add this project to [Made-In-Senegal repo](https://github.com/GalsenDev221/made.in.senegal) you can see that on : https://www.madeinsenegal.dev

**Comment by mr-mib** [comment]
Thanks. I saw i!

Could you share it with your network so they could participate on this amazing project

**Comment by daoodaba975** [comment]
> Thanks. I saw i!
> 
> Could you share it with your network so they could participate on this amazing project

No worries I will do it!

**Pull request merged**
